// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVMfGK15X52CZMREU-GFTGw1qQJoHYIk',
    appId: '1:829632593359:web:502428d1829061532966ba',
    messagingSenderId: '829632593359',
    projectId: 'e-commerce-b66a6',
    authDomain: 'e-commerce-b66a6.firebaseapp.com',
    storageBucket: 'e-commerce-b66a6.firebasestorage.app',
    measurementId: 'G-BZ4P9TRWKX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRHmVKDub6EuklqkeqDCdcXth5MZHgQCo',
    appId: '1:829632593359:ios:eb29f3963978b5922966ba',
    messagingSenderId: '829632593359',
    projectId: 'e-commerce-b66a6',
    storageBucket: 'e-commerce-b66a6.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfVMfGK15X52CZMREU-GFTGw1qQJoHYIk',
    appId: '1:829632593359:web:6361cd6830049fc72966ba',
    messagingSenderId: '829632593359',
    projectId: 'e-commerce-b66a6',
    authDomain: 'e-commerce-b66a6.firebaseapp.com',
    storageBucket: 'e-commerce-b66a6.firebasestorage.app',
    measurementId: 'G-YSQCDREJ9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdr6vvdmqjIasyvmNLxhO7cRNT5uBzRz8',
    appId: '1:829632593359:android:fe73f43358953ebe2966ba',
    messagingSenderId: '829632593359',
    projectId: 'e-commerce-b66a6',
    storageBucket: 'e-commerce-b66a6.firebasestorage.app',
  );

}